exclude_paths:
  - tmp
  - vendor

detectors:
  FeatureEnvy:
    exclude:
      - "Tone::Decoder#scan"
  LongParameterList:
    enabled: false
  TooManyStatements:
    exclude:
      - "Tone::Decoder#scan"
